name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  retrofit: ^4.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  dio: ^5.8.0+1
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true